/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'jacobheldenbrand' at '6/29/16 3:22 PM' with Gradle 2.14
 *
 * @author jacobheldenbrand, @date 6/29/16 3:22 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
